/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import controller.CrudClienteController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteban
 */
public class CrudCliente extends javax.swing.JFrame {
    DefaultTableModel modelo;
    CrudClienteController crudClienteController;
    
    /**
     * Creates new form CrudCliente
     */
    public CrudCliente() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Identificacion");
        modelo.addColumn("Direccion");
        modelo.addColumn("Telefono");
        modelo.addColumn("Tipo");
        modelo.addColumn("Email");
        modelo.addColumn("Fecha de nacimiento");
        modelo.addColumn("Nit");
        modelo.addColumn("Identificacion tributaria");
        this.tabla.setModel(modelo);
        labelDato1.setText("");
        textDato1.setEnabled(false);
        labelDato2.setText("");
        textDato2.setEnabled(false);
        crudClienteController = new CrudClienteController();
        String[][] info = crudClienteController.readListaCliente();
        translateTable(info);
    }
    
    public void translateTable(String[][] info){
        for(int i = 0; i<info.length;i++){
            if(!(info[i][5].equals("Natural"))){
               info[i][6] = null;
               info[i][7] = null;
            }
            if(!(info[i][5].equals("Juridica"))){
               info[i][8] = null;
               info[i][9] = null;
            }
        }
        for(int i = 0; i<info.length; i++){
            modelo.addRow(info[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTelefono = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();
        labelDato1 = new javax.swing.JLabel();
        textDato1 = new javax.swing.JTextField();
        labelDato2 = new javax.swing.JLabel();
        labelCampo = new javax.swing.JLabel();
        botonBorrar = new javax.swing.JButton();
        dropDownPosicion = new javax.swing.JComboBox<>();
        labelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        labelFila = new javax.swing.JLabel();
        textFilaEliminacion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        labelValorEditar = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        textValorEditar = new javax.swing.JTextField();
        botonAgregar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        dropDownTipo = new javax.swing.JComboBox<>();
        labelApellido = new javax.swing.JLabel();
        textApellido = new javax.swing.JTextField();
        labelIdentificacion = new javax.swing.JLabel();
        textIdentificacion = new javax.swing.JTextField();
        labelDireccion = new javax.swing.JLabel();
        textDireccion = new javax.swing.JTextField();
        labelTelefono = new javax.swing.JLabel();
        textDato2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTipo.setText("Tipo:");

        labelDato1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDato1.setText("Dato1:");

        labelDato2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDato2.setText("Dato2:");

        labelCampo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCampo.setText("Campo:");

        botonBorrar.setLabel("Borrar");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        dropDownPosicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Nombre", "Apellido", "Identificacion", "Direccion", "Telefono", "Tipo", "Email", "Fecha nacimiento", "NIT", "Identificacion tributaria" }));
        dropDownPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownPosicionActionPerformed(evt);
            }
        });

        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombre.setText("Nombre:");
        labelNombre.setToolTipText("");

        labelFila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFila.setText("Fila:");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Identificacion", "Direccion", "Telefono", "Tipo", "Email", "Fecha nacimiento", "NIT", "Identificacion tributaria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(9).setResizable(false);
        }

        labelValorEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelValorEditar.setText("Valor:");

        botonVolver.setLabel("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        textValorEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textValorEditarActionPerformed(evt);
            }
        });

        botonAgregar.setLabel("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonEditar.setLabel("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        dropDownTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Natural", "Juridica" }));
        dropDownTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownTipoActionPerformed(evt);
            }
        });

        labelApellido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApellido.setText("Apellido:");

        labelIdentificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIdentificacion.setText("Id:");

        labelDireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDireccion.setText("Direccion:");

        labelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTelefono.setText("Telefono:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(labelIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(8, 8, 8)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(textIdentificacion)
                                                .addComponent(textDireccion)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(8, 8, 8)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(textApellido)
                                                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelDato1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                        .addComponent(labelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                        .addComponent(labelDato2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(8, 8, 8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                        .addComponent(dropDownTipo, 0, 146, Short.MAX_VALUE)
                                        .addComponent(textDato1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                        .addComponent(textDato2)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(190, 190, 190)
                                    .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(258, 258, 258)
                                    .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(198, 198, 198))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelValorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textFilaEliminacion)
                                        .addComponent(dropDownPosicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textValorEditar))
                                    .addGap(41, 41, 41)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonVolver)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelNombre)
                                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelApellido)
                                        .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelIdentificacion)
                                        .addComponent(textIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelDato1)
                                        .addComponent(textDato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelTelefono)
                                        .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelTipo)
                                        .addComponent(dropDownTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelDireccion)
                                .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDato2)
                            .addComponent(textDato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelFila)
                            .addComponent(textFilaEliminacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dropDownPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCampo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelValorEditar)
                            .addComponent(textValorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregar)
                    .addComponent(botonEditar)
                    .addComponent(botonBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        int fila = tabla.getSelectedRow();
        if(fila >=0){
            modelo.removeRow(fila);
            crudClienteController.deleteCliente(fila);
        }
        crudClienteController.writeListaCliente();
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void textValorEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textValorEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textValorEditarActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
        InterfazBase interfazBase = new InterfazBase();
        interfazBase.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed
    
    private boolean verifyDataChanged(){
        return !(textFilaEliminacion.getText().equals("") && textValorEditar.getText().equals("") 
                && dropDownPosicion.getSelectedItem().equals("Seleccionar"));
    }
    
    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        if(verifyDataChanged()){
            int fila = Integer.parseInt(textFilaEliminacion.getText());
            int columna = dropDownPosicion.getSelectedIndex();
            String valor = textValorEditar.getText();
            if(columna == 6 && ( valor.equals("Natural") || valor.equals("Juridica"))){
                modelo.setValueAt(valor, fila-1, columna-1);
                crudClienteController.editCliente(fila-1, columna, valor);
                crudClienteController.writeListaCliente();
                if (!(valor.equals("Natural"))){
                    modelo.setValueAt(null, fila-1, 6);
                    modelo.setValueAt(null, fila-1, 7);
                    crudClienteController.editCliente(fila-1, 7, null);
                    crudClienteController.editCliente(fila-1, 8, null);
                    crudClienteController.writeListaCliente();
                }
                if(!(valor.equals("Juridica"))){
                    modelo.setValueAt(null, fila-1, 8);
                    modelo.setValueAt(null, fila-1, 9);
                    crudClienteController.editCliente(fila-1, 9, null);
                    crudClienteController.editCliente(fila-1, 10, null);
                    crudClienteController.writeListaCliente();
                }
                
                }else{
                if((columna == 7 || columna == 8) && modelo.getValueAt(fila-1, 5).equals("Natural")){
                    modelo.setValueAt(valor, fila-1, columna-1);
                    crudClienteController.editCliente(fila-1, columna, valor);
                    crudClienteController.writeListaCliente();
                }else{
                    if((columna == 9 || columna == 10) && modelo.getValueAt(fila-1, 5).equals("Juridica")){
                        modelo.setValueAt(valor, fila-1, columna-1);
                        crudClienteController.editCliente(fila-1, columna, valor);
                        crudClienteController.writeListaCliente();
                    }else{
                        if(columna>0 && columna<6){
                            modelo.setValueAt(valor, fila-1, columna-1);
                            crudClienteController.editCliente(fila-1, columna, valor);
                            crudClienteController.writeListaCliente();
                        }
                    }
                }
            }
        }    
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
               if(verifyEmpty()){
            String[] info = new String[10];
            info[0]=textNombre.getText();
            info[1]=textApellido.getText();
            info[2]=textIdentificacion.getText();
            info[3]=textDireccion.getText();
            info[4]=textTelefono.getText();
            String aux = dropDownTipo.getSelectedItem().toString();
            info[5]= aux;
            if(aux == "Natural"){
                info[6] = textDato1.getText();
                info[7] = textDato2.getText();
                textDato1.setText("");
                labelDato1.setText("");
                textDato1.setEnabled(false);
                textDato2.setText("");
                labelDato2.setText("");
                textDato2.setEnabled(false);
            }else{
                if(aux == "Juridica"){
                    info[8] = textDato1.getText();
                    info[9] = textDato2.getText();
                    textDato1.setText("");
                    textDato2.setText("");
                    labelDato1.setText("");
                    textDato1.setEnabled(false);
                    labelDato2.setText("");
                    textDato2.setEnabled(false);
                }
            }
            modelo.addRow(info);
            
            textNombre.setText("");
            textApellido.setText("");
            textIdentificacion.setText("");
            textDireccion.setText("");
            textTelefono.setText("");
            dropDownTipo.setSelectedIndex(0);
           crudClienteController.addCliente(info);
           crudClienteController.writeListaCliente();
        }
    }//GEN-LAST:event_botonAgregarActionPerformed

     private boolean verifyEmpty(){
        return !(textApellido.getText().equals("") && textNombre.getText().equals("") && textIdentificacion.getText().equals("") 
                && textDireccion.getText().equals("") && textTelefono.getText().equals("") 
                && dropDownTipo.getSelectedItem().equals("Seleccionar"));
    }
     
    private void dropDownTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownTipoActionPerformed
        String aux = dropDownTipo.getSelectedItem().toString();
        if(aux == "Natural"){
            labelDato1.setText("Email:");
            textDato1.setEnabled(true);
            labelDato2.setText("Fecha de nacimiento");
            textDato2.setEnabled(true);
        }else{
            if(aux == "Juridica"){
                labelDato1.setText("Nit:");
                labelDato2.setText("Identificacion tributaria:");
                textDato1.setEnabled(true);
                textDato2.setEnabled(true);
            }
        }
    }//GEN-LAST:event_dropDownTipoActionPerformed

    private void dropDownPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropDownPosicionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JComboBox<String> dropDownPosicion;
    private javax.swing.JComboBox<String> dropDownTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelCampo;
    private javax.swing.JLabel labelDato1;
    private javax.swing.JLabel labelDato2;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelFila;
    private javax.swing.JLabel labelIdentificacion;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelValorEditar;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textDato1;
    private javax.swing.JTextField textDato2;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textFilaEliminacion;
    private javax.swing.JTextField textIdentificacion;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTelefono;
    private javax.swing.JTextField textValorEditar;
    // End of variables declaration//GEN-END:variables
}
